language: java

sudo: false # faster builds


cache:
  directories:
    - $HOME/.m2

install: true

script:
  - travis_wait 30 mvn clean install -DskipTests=true -Dcheckstyle.skip=true -Dmaven.javadoc.skip=true
